- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: NMAP | Installing NMAP
      yum:
        name: nmap
        state: latest
