- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: NMAP | Installing NMAP
      yum:
        name: nmap
        state: latest
    - name: install basic packages
      action: >
          yum: name={{ item }} state=present
      with_items:
        - vim
        - bind-utils
        - mc
        - wget
        - krb5-workstation
