- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: NMAP | Installing NMAP
      yum:
        name: nmap
        state: latest
    - name: install basic packages
      action: >
         {{ ansible_pkg_mgr }} name={{ item }} state=present
      with_items:
        - vim
        - bind-utils
        - mc
        - wget
        - krb5-workstation
        - sssd-client 
        - sssd-common 
        - sssd-ldap 
        - sssd-krb5-common 
        - sssd-krb5 
        - openldap-clients
    - copy: 
        src: /srv/myfiles/crt_import.sh
        dest: /root/crt_import.sh
        owner: root
        group: root
        mode: 0700
    - name: Export Certificate
      command: /root/crt_import.sh

