- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: NMAP | Installing NMAP
      yum:
        name: nmap
        state: latest
    - name: install basic packages
      action: >
         {{ ansible_pkg_mgr }} name={{ item }} state=present
      with_items:
        - vim
        - bind-utils
        - mc
        - wget
        - krb5-workstation
        - sssd-client 
        - sssd-common 
        - sssd-ldap 
        - sssd-krb5-common 
        - sssd-krb5 
        - openldap-clients
    - name: Export Certificate
      command: 'echo -n | openssl s_client -connect 192.168.133.95:636 | sed -ne \'/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p\' > /root/ldapserver.pem && certutil -A -i /root/ldapserver.pem -n "Samba Administration" -t "CTu,u,u" -d . -p password'
