- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: NMAP | Installing NMAP
      yum:
        name: nmap
        state: latest
    - names: Install needed packages
      yum: name={{item}} state=installed
          with_items:
                - vim
                - bind-utils
                - mc
                - wget
                - krb5-workstation

