- name: Hello World Sample
  hosts: all
  tasks:
   - names: Install needed packages
     yum: name={{item}} state=installed
     with_items:
        - vim
        - bind-utils
        - mc
        - wget
        - krb5-workstation
